### ISSUE TITLE
Diffs on array entities return reference to original array

### ISSUE THREAD

**Issue by andrew-tam-000** [mattphillips/deep-object-diff#15]
Here's an example:

```
var deepObjectDiff = require("deep-object-diff")

var orig = {}

var updated = {
    four: ['hello', 'byebye']
};

var diff = deepObjectDiff.diff(orig, updated);

delete diff.four[0];

console.log(diff, updated);

```
What I expect to see is that after deleting the key from the 'diff', my 'updated' variable should remain unchanged.  However, because 'diff' is returning a reference to the array that got updated, when I delete the an array entry from 'diff', it mutates 'updated'.

Any chance we can get this fixed?

Thanks!

**Comment by mattphillips** [comment]
Hey @andrew-tam-000 thanks for raising the issue. 

This is an interesting problem and ideally this package would copy by value and not reference. There is a bit of overhead to deep cloning objects and wouldn't be something that I am able to look into right now.

What you could do as a quick fix is either of the following: 

1. Use `JSON.parse(JSON.stringify(obj))`:
```js
var deepObjectDiff = require("deep-object-diff")

var orig = {}

var updated = {
    four: ['hello', 'byebye']
};

var diff = JSON.parse(JSON.stringify(deepObjectDiff.diff(orig, updated)));

delete diff.four[0];

console.log(diff, updated);
```
_Note: the only issue with this approach is that you can only deep clone simple objects (ie. no prototypes, functions or circular references)_

2. Use [lodash deep clone](https://lodash.com/docs/4.17.4#cloneDeep):
```js
var deepObjectDiff = require("deep-object-diff")
var cloneDeep = require("lodash/fp/cloneDeep")
var orig = {}

var updated = {
    four: ['hello', 'byebye']
};

var diff = cloneDeep(deepObjectDiff.diff(orig, updated));

delete diff.four[0];

console.log(diff, updated);
```
_Note: the only issue with this approach is that there is an additional dependency_

Either of the above approach will fix your issue 😄

**Comment by andrew-tam-000** [comment]
Hey man, thanks for the quick response XD. Cool yea -- I was just stringifying and then parsing it, but maybe I'll stick with lodash's cloneDeep as you recommended, as its less verbose and I'm already using lodash.
