### ISSUE TITLE
delete return value

### ISSUE THREAD

**Issue by edwardsmarkf** [mattphillips/deep-object-diff#2]
could we include [this gist](https://gist.github.com/mattphillips/d6634fb745cae541288fe023e0c7e7a5#file-detaileddiffdeletedtonull-js-L13) with deep-object-diff and use a parameter with `detailedDifference(` function?

something like:

```
detailedDifference(lhs, rhs, null);   // return null rather than undefined
detailedDifference(lhs, rhs, '{}' ) ;   // return {} rather than undefined
```

**Comment by mattphillips** [comment]
I think the value of `undefined` has the correct semantic meaning in that the value has been deleted and is now `undefined`. This change would also mean changing the API for 2 of the 5 available functions (`deletedDiff` and `detailedDiff`) which ideally would all remain the same.

I've just updated the gist to use the correct variable name on line 32 - which shows how to map the `undefined` values to a `null`.
