### ISSUE TITLE
deletedDiff returns undefined values that are not JSON valid

### ISSUE THREAD

**Issue by boshka** [mattphillips/deep-object-diff#27]
Could there be an option that would result in deletedDiff returning other values, such as null instead of undefined?

**Comment by mattphillips** [comment]
Hey @boshka this sounds similar to this issue #10 what you can do is supply a replacer function to JSON.stringify to convert the undefined values to null or anything you like. There is an example of this in action in #10 

Let me know if that solves your problem

**Comment by boshka** [comment]
Hi Matt,
sorry, did not notice that solution. Thank you, that works!
