### ISSUE TITLE
node_modules/deep-object-diff/dist/index.js: Unknown plugin "add-module-exports" specified in package.json

### ISSUE THREAD

**Issue by tigranbalayan** [mattphillips/deep-object-diff#33]
can not bundle with react-native

**Comment by mattphillips** [comment]
HI @tigranbalayan would you be able to supply a minimal repo with a reproduction?

All you should need to do is either:

```js
const { diff } = require('deep-object-diff');

// OR

import { diff } from 'deep-object-diff';
```

`add-module-exports` plugin is used by `deep-object-diff` to build the package and should never be exposed to users of the package

**Comment by ericconstantinides** [comment]
I got the same error. A quick fix was to delete the "babel" portion from the deep-object-diff's package.json. I'm sure @mattphillips has a better solution but this worked in the interim.
