### ISSUE TITLE
extend logic for updatedDiff

### ISSUE THREAD

**Issue by yurks** [mattphillips/deep-object-diff#36]
For now .updatedDiff() method returns summary of updated keys with actual values.
All seems correct, but.. 
We _already_ have new fresh object received with all _actual_ data inside. Imagine we would like to save it and overwrite an old data. And wand to preserve changes history. No chance to get _previous_ data for updated keys for now. 

Maybe .updatedDiff(oldObj, newObj, [showOldValuesForUpdatedKeys= true|false ] )?

**Comment by mattphillips** [comment]
Hey @yurks I'm not sure I understand what you are asking. Would you be able to give me an example of what you want?

**Comment by mattphillips** [comment]
Closing for now due to inactivity - happy to reopen with more details
