### ISSUE TITLE
Does not detect differences in order

### ISSUE THREAD

**Issue by giorgio79** [mattphillips/deep-object-diff#42]
When diffing two objects where I would like the order of keys to matter:
```

const { diff, addedDiff, deletedDiff, detailedDiff, updatedDiff } = require("deep-object-diff");

const right = {
1: "Tom",
2: "reads",
3: ",",
4: "novels"
};

const wrong = {
1: "Tom",
2: "reads",
3: "novels",
4: ","
};

console.log(detailedDiff(right, wrong)); 

```
And the result is:

`Object {added: , deleted: , updated: }`

**Comment by mattphillips** [comment]
Seems to working fine check out: https://runkit.com/embed/uy9n61eue7s3

It logs:

```
added: Object {}
deleted: Object {}
updated: Object {3: "novels", 4: ","}
```

**Comment by giorgio79** [comment]
Right! Thanks and sry! :) I did not click the arrow to expand the result:

![image](https://user-images.githubusercontent.com/283347/48412357-b0837e00-e744-11e8-9ec6-0f974647f5ab.png)


![image](https://user-images.githubusercontent.com/283347/48412342-a792ac80-e744-11e8-9ea3-4a2f1aa67561.png)
