### ISSUE TITLE
Undefined value

### ISSUE THREAD

**Issue by josinaldobarbosa** [mattphillips/deep-object-diff#54]
should that be undefined?

Original: `[ { _id: 123, id_content: 111, id_category: 22 } ]`
New: `[ { id_content: 111, id_category: 22 } ]`
detailedDiff/diff: `{ added: {}, deleted: { '0': { _id: undefined } }, updated: {} }`

**Comment by papb** [comment]
Yes, this is the way this module works, it outputs the current value, since `_id` no longer exists, its current value resolves to undefined.

**Comment by anko** [comment]
Yep, I think that's the expected behaviour. [The readme `deletedDiff` example](https://github.com/mattphillips/deep-object-diff#deleteddiff) works the same way.

**Comment by josinaldobarbosa** [comment]
ok, thanks guys
