### ISSUE TITLE
Use ECMAScript modules instead of CommonJS modules

### ISSUE THREAD

**Issue by rallets** [mattphillips/deep-object-diff#57]
Hi, building an Angular project with the latest version 10.0.7 I got this warning message
WARNING in C:\[...]\filename.ts depends on 'deep-object-diff'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies

Is there any chance this library to be convert to ECMAScript modules? This will allow for a greater bundle size optimization at build time for apps that uses webpack or similar minifiers (https://web.dev/commonjs-larger-bundles/).

Thanks

**Comment by mattphillips** [comment]
Sorry to come to so long after you raised the issue @rallets!

I've just played with publishing the module with ES module support - would be great if you (or anyone) could confirm it's working. Should be available in [v1.1.5](https://www.npmjs.com/package/deep-object-diff/v/1.1.5)

**Comment by rallets** [comment]
Hi @mattphillips, great to hear you published a new version. 
Unfortunately I'm not working anymore on that project, so I don't have access to the source code to test it's working as it should.

**Comment by mattphillips** [comment]
@rallets no worries at all - I just did a manual test with node and it seems to be OK. 

I'll close this issue for now and if anyone runs into this issue again then feel free to comment or PR a fix 😅

Thanks for your quick reply @rallets
