### ISSUE TITLE
Wrong diff changing an undefined attribute to empty object

### ISSUE THREAD

**Issue by filipealonso** [mattphillips/deep-object-diff#66]
When you check against removed or undefined attributes it works fine:
:heavy_check_mark: `diff({a:{}}, {a:undefined})` returns `{a: undefined}`
:heavy_check_mark: `diff({a:{}}, {})` returns `{a: undefined}`

But when you invert and add/change to an empty object it differs depending if it was undefined or nonexistent before:
:heavy_check_mark: `diff({}, {a:{}})` returns `{a:{}}`
:x: `diff({a:undefined}, {a:{}})` returns `{}` instead of `{a:{}}`

**Comment by mattphillips** [comment]
Thanks @filipealonso I'll get this published shortly

**Comment by mattphillips** [comment]
Fix available in https://www.npmjs.com/package/deep-object-diff/v/1.1.5
