### ISSUE TITLE
an option to detect "inserted" and removed items in arrays

### ISSUE THREAD

**Issue by DetachHead** [mattphillips/deep-object-diff#86]
```ts
diff(['a', 'c', 'd', 'e'], ['a', 'b', 'c', 'd', 'e'])
```
the current behavior is to treat indexes 1, 2 and 3 as changed and 4 as added
```ts
{ '1': 'b', '2': 'c', '3': 'd', '4': 'e' }
```
it would be nice if it was able to detect that only one value was added. something like this:
```ts
{ inserts: { 1: 'b' } }
```

**Comment by anko** [comment]
Duplicate?: https://github.com/mattphillips/deep-object-diff/issues/60

**Comment by DetachHead** [comment]
duplicate of #60 i guess
