### ISSUE TITLE
hasOwnProperty is not a function

### ISSUE THREAD

**Issue by lucianobosco** [mattphillips/deep-object-diff#89]
Since last update I'm getting `hasOwnProperty is not a function`
I used to create a payload with differences to be sent to my API through axios:

```
      const diffs = diff(originalResource.value, resource.value)
      const payload = {
        ...(diffs.hasOwnProperty('name') && { name: resource.value.name }),
        ...(diffs.hasOwnProperty('slug') && { slug: resource.value.slug }),
        ...(diffs.hasOwnProperty('visible') && { visible: resource.value.visible }),
        ...(diffs.hasOwnProperty('postCategory') && { post_category_id: resource.value.postCategory?.id || null }),
        ...(diffs.hasOwnProperty('parent') && { parent_id: resource.value.parent?.id || null })
      }
```
Did anything change in regards to returned response from method `diff()`. In that case, how can I get `diff()` properties changed in order to create a new payload object?

**Comment by mattphillips** [comment]
Hi @lucianobosco due to a potential vulnerability with unsafely setting the diffed properties on the returned diff object, the diffed object is now created using `Object.create(null)`. This means that the returned diffed object has no prototype and so `hasOwnProperty` will be undefined.

In your case you could spread the diff object into another object with the default prototype functions available.


```js
      const diffs = diff(originalResource.value, resource.value)
      const d = { ...diffs }
      const payload = {
        ...(d.hasOwnProperty('name') && { name: resource.value.name }),
        ...(d.hasOwnProperty('slug') && { slug: resource.value.slug }),
        ...(d.hasOwnProperty('visible') && { visible: resource.value.visible }),
        ...(d.hasOwnProperty('postCategory') && { post_category_id: resource.value.postCategory?.id || null }),
        ...(d.hasOwnProperty('parent') && { parent_id: resource.value.parent?.id || null })
      }
```

**Comment by lucianobosco** [comment]
> Hi @lucianobosco due to a potential vulnerability with unsafely setting the diffed properties on the returned diff object, the diffed object is now created using `Object.create(null)`. This means that the returned diffed object has no prototype and so `hasOwnProperty` will be undefined.
> 
> In your case you could spread the diff object into another object with the default prototype functions available.
> 
> ```js
>       const diffs = diff(originalResource.value, resource.value)
>       const d = { ...diffs }
>       const payload = {
>         ...(d.hasOwnProperty('name') && { name: resource.value.name }),
>         ...(d.hasOwnProperty('slug') && { slug: resource.value.slug }),
>         ...(d.hasOwnProperty('visible') && { visible: resource.value.visible }),
>         ...(d.hasOwnProperty('postCategory') && { post_category_id: resource.value.postCategory?.id || null }),
>         ...(d.hasOwnProperty('parent') && { parent_id: resource.value.parent?.id || null })
>       }
> ```

Thanks a lot! That works

**Comment by JuanJo4** [comment]
Note that inner objects doesn't have prototype too, so even if you spread the object you might face the same `hasOwnProperty is not a function` error.

```javascript
const diffs = diff(originalResource.value, resource.value)
const d = { ...diffs }

d.innerObj.hasOwnProperty('myProp') // will throw hasOwnProperty is not a function
```

A different solution than spreading the diff object could be to use `Object.hasOwnProperty.call` directly, like this:

```javascript
Object.hasOwnProperty.call(diffs, prop)
```
